import type { Product } from '@/lib/supabase/types'

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'sample-1',
    name: 'Levitation Lounge Chair',
    slug: 'levitation-lounge-chair',
    description: 'The pinnacle of ergonomic design meets ethereal aesthetics.',
    price: 2499,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 12,
    created_at: '',
    categories: { id: '1', name: 'Furniture', slug: 'furniture', image_url: null, created_at: '' },
  },
  {
    id: 'sample-2',
    name: 'Halo Table Lamp',
    slug: 'halo-table-lamp',
    description: 'A quiet glow for reading corners, consoles, and bedside rituals.',
    price: 899,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 25,
    created_at: '',
    categories: { id: '2', name: 'Lighting', slug: 'lighting', image_url: null, created_at: '' },
  },
  {
    id: 'sample-3',
    name: 'Onyx Timepiece',
    slug: 'onyx-timepiece',
    description: 'Precision engineered from a single block of volcanic glass.',
    price: 499,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 40,
    created_at: '',
    categories: { id: '3', name: 'Accessories', slug: 'accessories', image_url: null, created_at: '' },
  },
  {
    id: 'sample-4',
    name: 'Zenith Ceramic Set',
    slug: 'zenith-ceramic-set',
    description: 'Seven uniquely textured vessels inspired by geological formations.',
    price: 320,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 15,
    created_at: '',
    categories: { id: '4', name: 'Decor', slug: 'decor', image_url: null, created_at: '' },
  },
]
