import type { Product } from '@/lib/supabase/types'

export const FALLBACK_PRODUCTS: Product[] = [
  // Furniture
  {
    id: 'sample-1',
    name: 'Levitation Lounge Chair',
    slug: 'levitation-lounge-chair',
    description: 'The pinnacle of ergonomic design meets ethereal aesthetics. Hand-crafted from sustainable oak and premium cloud-weave fabric.',
    price: 2499,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 12,
    created_at: '',
    categories: { id: '1', name: 'Furniture', slug: 'furniture', image_url: null, created_at: '' },
  },
  {
    id: 'sample-5',
    name: 'Travertine Coffee Table',
    slug: 'travertine-coffee-table',
    description: 'Crafted from solid Italian travertine stone with a honed finish. Features rounded pillar legs and a soft, tactile surface that highlights natural geological texture.',
    price: 1850,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 8,
    created_at: '',
    categories: { id: '1', name: 'Furniture', slug: 'furniture', image_url: null, created_at: '' },
  },
  {
    id: 'sample-6',
    name: 'Minimalist Bouclé Sofa',
    slug: 'minimalist-boucle-sofa',
    description: 'A low-profile modular sofa upholstered in a luxurious, textured cream bouclé fabric. Soft curves meet structured geometric lines for a calm lounge experience.',
    price: 3400,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 4,
    created_at: '',
    categories: { id: '1', name: 'Furniture', slug: 'furniture', image_url: null, created_at: '' },
  },

  // Lighting
  {
    id: 'sample-2',
    name: 'Halo Table Lamp',
    slug: 'halo-table-lamp',
    description: 'A quiet glow for reading corners, consoles, and bedside rituals. The Halo uses advanced diffusion technology to create a shadowless glow.',
    price: 899,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 25,
    created_at: '',
    categories: { id: '2', name: 'Lighting', slug: 'lighting', image_url: null, created_at: '' },
  },
  {
    id: 'sample-7',
    name: 'Alabaster Sconce',
    slug: 'alabaster-sconce',
    description: 'Carved solid Spanish alabaster cylinder mounted on a brushed brass fixture. Emits a warm, marbled light showing the natural veins of the stone.',
    price: 420,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 18,
    created_at: '',
    categories: { id: '2', name: 'Lighting', slug: 'lighting', image_url: null, created_at: '' },
  },
  {
    id: 'sample-8',
    name: 'Sculptural Floor Lamp',
    slug: 'sculptural-floor-lamp',
    description: 'Hand-spun steel base with an adjustable matte black arm and dome shade. A functional sculpture providing direct task lighting and indirect ambient reflection.',
    price: 750,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 10,
    created_at: '',
    categories: { id: '2', name: 'Lighting', slug: 'lighting', image_url: null, created_at: '' },
  },

  // Accessories
  {
    id: 'sample-3',
    name: 'Onyx Timepiece',
    slug: 'onyx-timepiece',
    description: 'Precision engineered from a single block of volcanic glass. A statement of timeless minimalism.',
    price: 499,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 40,
    created_at: '',
    categories: { id: '3', name: 'Accessories', slug: 'accessories', image_url: null, created_at: '' },
  },
  {
    id: 'sample-9',
    name: 'Brushed Brass Catchall',
    slug: 'brushed-brass-catchall',
    description: 'Solid cast brass dish, hand-polished with a brushed satin finish. Designed for entryways, desks, or nightstands to hold daily essentials.',
    price: 180,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1532635211-8ec15f2ce05c?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 35,
    created_at: '',
    categories: { id: '3', name: 'Accessories', slug: 'accessories', image_url: null, created_at: '' },
  },
  {
    id: 'sample-10',
    name: 'Leather Desk Mat',
    slug: 'leather-desk-mat',
    description: 'Made from vegetable-tanned full-grain leather that will develop a rich patina over time. Smooth surface with hand-stitched details.',
    price: 220,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 20,
    created_at: '',
    categories: { id: '3', name: 'Accessories', slug: 'accessories', image_url: null, created_at: '' },
  },

  // Decor
  {
    id: 'sample-4',
    name: 'Zenith Ceramic Set',
    slug: 'zenith-ceramic-set',
    description: 'Seven uniquely textured vessels inspired by geological formations. A centerpiece for the modern home.',
    price: 320,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 15,
    created_at: '',
    categories: { id: '4', name: 'Decor', slug: 'decor', image_url: null, created_at: '' },
  },
  {
    id: 'sample-11',
    name: 'Merino Wool Throw',
    slug: 'merino-wool-throw',
    description: 'Woven from ultra-soft Australian Merino wool in a quiet sand and charcoal grid pattern. Finished with delicate fringed edges.',
    price: 290,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 30,
    created_at: '',
    categories: { id: '4', name: 'Decor', slug: 'decor', image_url: null, created_at: '' },
  },
  {
    id: 'sample-12',
    name: 'Stoneware Ribbed Vase',
    slug: 'stoneware-ribbed-vase',
    description: 'Wheel-thrown stoneware featuring a deeply ribbed tactile surface and a textured matte white glaze. Beautiful with simple branches or as a standalone piece.',
    price: 145,
    category_id: null,
    images: ['https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?auto=format&fit=crop&q=80&w=600'],
    is_active: true,
    stock: 22,
    created_at: '',
    categories: { id: '4', name: 'Decor', slug: 'decor', image_url: null, created_at: '' },
  },
]
